import Nav from './components/Nav';
import TopNav from './components/TopNav';
import './global.css';

export const metadata = {
    title: "Won's Space",
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="global">
                <TopNav />
                {children}
                <Nav />
            </body>
        </html>
    );
}
